In [1]:
import sys
%load_ext autoreload
%autoreload 2
import cv2
import matplotlib.pyplot as plt
%matplotlib inline

sys.path.append("../")
from vision.yolo.darknet53 import DarkNet53, Conv_Bn_Leaky, DarkNetBlock
from vision.yolo.yolov3 import create_net


from vision.yolo.yolo_config import Config
cfg = Config()

import torch
img = torch.ones(1,3,416,416)
import torch.nn as nn

In [2]:
# data loader
from torch.utils import data
from vision.yolo.yolov3 import MultiboxLoss
from vision.yolo.voc_dataset import detection_collate, VOCDetection
train_dataset = VOCDetection("../../YOLOv3_Pytorch/data/datasets/VOCdevkit0712", [('0712', '0712_trainval')], (416, 416), 3, True, "VOC")


In [3]:

batch_iterator = iter(data.DataLoader(train_dataset, 
                                      3,
                                      shuffle=True,
                                      num_workers=4,
                                      collate_fn=detection_collate))

net = create_net(cfg, is_test=False)
net.cuda()
img, target = next(batch_iterator)
img = img.cuda()

out = net(img)

det torch.Size([3, 507, 85]) 13 32 507
det torch.Size([3, 2028, 85]) 26 16 2028
det torch.Size([3, 8112, 85]) 52 8 8112


/home/yhosoya/anaconda3/lib/python3.6/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))


In [6]:
add_sigmoid, add_sigmoid_offsef = out

In [5]:
mloss = MultiboxLoss(cfg)

In [7]:
mloss(add_sigmoid, add_sigmoid_offsef, target, debug=True)

1:fore_mask_t tensor([[112, 164,  36,  ..., 109, 127,   0],
        [  0,  43,  19,  ...,   0,   0,   0],
        [  0,   0,   0,  ...,   0,   0,   0]], device='cuda:0',
       dtype=torch.uint8)
cuda False False
cuda False False
cuda False False
2:fore_mask_t tensor([[0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]], device='cuda:0', dtype=torch.uint8)
xy_loss 1.8345 wh_loss 0.99297 cls_loss 75.12937 ave_cls 0.47188 Obj 0.42312 no_obj 0.50793 fore_conf_loss 3.5771 back_conf_loss 22802.49609


../vision/yolo/yolov3.py:337: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  cls_fore_mask_t = fore_mask_t.new_tensor(fore_mask_t).view(batch_size, num_pred, 1).expand_as(cls_pred)


tensor(7678.0962, device='cuda:0', grad_fn=<AddBackward0>)

In [ ]:
with open("../../YOLOv3_Pytorch/weights_trained/convert_darknet53.pth", )

In [17]:
weight = torch.load("../../YOLOv3_Pytorch/weights_trained/convert_darknet53.pth")
# for i in weight.keys():
#     print(weight[i].shape)
len(weight)

260

In [23]:
import pickle
with open("../../YOLOv3_Pytorch/eval/aeroplane_pr.pkl", "rb") as f:
    out = pickle.load(f)


In [33]:
import numpy as np

np.array([0.229, 0.224, 0.225])*255

array([58.395, 57.12 , 57.375])

In [53]:
# demo.py, images/dog.jpg

torch.Size([1, 10647, 25])
tensor([[1.7449e+01, 1.9058e+01, 9.4442e+01, 7.6652e+01, 1.1803e-07],
        [1.3544e+01, 1.7641e+01, 1.4986e+02, 1.8285e+02, 1.1748e-07],
        [1.4749e+01, 1.6207e+01, 3.6843e+02, 3.4552e+02, 3.6790e-07]],
       device='cuda:0')

# fragment.py, images/dog.jpg
torch.Size([1, 10647, 25])
tensor([[1.7449e+01, 1.9058e+01, 9.4442e+01, 7.6652e+01, 1.1803e-07],
        [1.3544e+01, 1.7641e+01, 1.4986e+02, 1.8285e+02, 1.1748e-07],
        [1.4749e+01, 1.6207e+01, 3.6843e+02, 3.4552e+02, 3.6790e-07]],
       device='cuda:0')



'models'

In [ ]:
# demo
detection_postprecess_fragment
[[110.464676   127.27025    555.2255     453.0021       0.99978393    0.99984264   1.        ]
 [474.4371      84.49383    672.11847    167.49568      0.99996555    0.99989295   6.        ]
 [123.11983    215.24858    306.22607    551.7865       0.99237096    0.97638875  11.        ]]


# fragment
detection_postprecess_fragment
tensor([[0.9999, 0.2108, 0.2366, 0.7306, 0.7669],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]], device='cuda:0')


In [55]:
normal
torch.Size([10647, 7])
tensor([0., 0., 0., 0., 0.], device='cuda:0')
tensor([ 1.,  6., 11.], device='cuda:0')



array([121.4208, 181.7088, 420.8256, 588.9792])

In [12]:
Evaluating detections
Writing aeroplane VOC results file
Writing bicycle VOC results file
Writing bird VOC results file
Writing boat VOC results file
Writing bottle VOC results file
Writing bus VOC results file
Writing car VOC results file
Writing cat VOC results file
Writing chair VOC results file
Writing cow VOC results file
Writing diningtable VOC results file
Writing dog VOC results file
Writing horse VOC results file
Writing motorbike VOC results file
Writing person VOC results file
Writing pottedplant VOC results file
Writing sheep VOC results file
Writing sofa VOC results file
Writing train VOC results file
Writing tvmonitor VOC results file
VOC07 metric? Yes
AP for aeroplane = 0.7992
AP for bicycle = 0.7962
AP for bird = 0.6904
AP for boat = 0.6530
AP for bottle = 0.6464
AP for bus = 0.7973
AP for car = 0.8650
AP for cat = 0.7864
AP for chair = 0.5724
AP for cow = 0.7435
AP for diningtable = 0.7032
AP for dog = 0.7429
AP for horse = 0.7940
AP for motorbike = 0.7937
AP for person = 0.7833
AP for pottedplant = 0.5206
AP for sheep = 0.7038
AP for sofa = 0.7023
AP for train = 0.7921
AP for tvmonitor = 0.7499
Mean AP = 0.7318
~~~~~~~~
Results:
0.799
0.796
0.690
0.653
0.646
0.797
0.865
0.786
0.572
0.743
0.703
0.743
0.794
0.794
0.783
0.521
0.704
0.702
0.792
0.750
0.732
~~~~~~~~



In [18]:
a(11, 9)

9